### ISSUE TITLE
Setup project template

### ISSUE THREAD

**Issue by surajverma2587** [talexandru1987/group-4-project-1#2]
### Tasks

- [ ] add files and folders
- [ ] add HTML and JS files for all pages of website
- [ ] import jQuery
- [ ] import CSS framework (investigate)
- [ ] import colour scheme (investigate)
- [ ] import google fonts (investigate)
- [ ] add .gitignore file
